PROGRAM=Cafe_v2.4

odczyt:
	java -jar $(PROGRAM).jar
dump:
	mysqldump -uroot -phackme -E -R --trigger --opt Cafesuite > backup/Cafesuite_`date +%d_%m_%y`.sql
push:
	mysql -uloper -phackme < inserty.sql
	rm inserty.sql
insert:
	echo "SELECT COUNT(*) FROM czasy" | mysql -uloper -phackme Cafesuite | awk 'NR==2' | xargs java -jar $(PROGRAM).jar -i
	mysql -uloper -phackme < inserty.sql
	rm inserty.sql
suma:
	echo "SELECT suma FROM suma" | mysql -uloper -phackme Cafesuite

